Repository Green-Software-Foundation/sci, pull requests merged in 2021-11, with the labels that each got.

#161 Updating the scope to reflect latest content
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, high

#163 Baseline comparison for savings
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, high

#165 fix typo
  README.md
Labels: documentation, low

#168 reordering
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, medium

#170 Change from R from "Baseline" to "Functional Unit"
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, medium

#172 spelling fixes in Readme
  README.md
Labels: documentation, low

#198 [Consistency Review] Yaml file updated with Alpha prefix
  Software_Carbon_Intensity/index.yaml
Labels: documentation, medium, alpha

#199 [Consistency Review] Minor grammar updates
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, medium, alpha

#201 [Consistency Review] Removed repeated verbiage in Quantification method section
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, medium, alpha
