Repository Green-Software-Foundation/sci, pull requests merged in 2021-09, with the labels that each got.

#70 Boundary Inclusion Requirement
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, minor-1, medium, requirements-constraints

#71 Energy Boundary
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, minor-1, medium, requirements-constraints

#69 Move action discussion
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, minor-0, medium

#73 added guidance on reporting the SCI value
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, minor-2, medium, requirements-constraints

#80 YAML file updated
  Software_Carbon_Intensity/Index.yaml
Labels: low

#75 Added systems footprint view for SCI and boundaries placeholder section
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, high, software-boundaries, requirements-constraints

#76 Added use of granular data for SCI calculation
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, high, requirements-constraints

#77 Added segment on choosing R value from a preset list
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, high, requirements-constraints

#79 Adding building, training, redundancy and failover to the boundary list
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, medium, software-boundaries, requirements-constraints

#82 added citation for the SCI
  CITATION.cff
Labels: documentation, medium

#84 Add orc-id for CLJ to file
  CITATION.cff
Labels: documentation, medium
