Repository Green-Software-Foundation/sci, pull requests merged in 2022-09, with the labels that each got.

#296 Update README.md
  README.md
Labels: minor-0

#297 Update Software_Carbon_Intensity_Specification.md
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: minor-0

#298 Update Software_Carbon_Intensity_Specification.md
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: minor-0

#299 Update Software_Carbon_Intensity_Specification.md
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: minor-0

#300 Update Software_Carbon_Intensity_Specification.md
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: minor-0

#318 Modified definitions section and linked dictionary
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, minor-2, consistency review

#320 Reorder Embodied Emissions Calculation
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, major-3, consistency review

#321 Change Reporting Requirement in Procedure
  Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Labels: documentation, major-3, consistency review
